package com.pharmacy.core.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class BaseEntityTest {

    // Concrete dummy implementation of BaseEntity for testing
    static class SampleEntity extends BaseEntity {
        public SampleEntity() {
            super();
        }
        public SampleEntity(String id) {
            super(id);
        }
    }

    @Test
    @DisplayName("BaseEntity auto-generates UUID if no ID is provided")
    void testAutoGeneratedId() {
        SampleEntity entity = new SampleEntity();
        assertNotNull(entity.getId());
        assertFalse(entity.getId().isEmpty());
        assertNotNull(entity.getCreatedAt());
        assertNotNull(entity.getUpdatedAt());
        assertTrue(entity.isActive());
    }

    @Test
    @DisplayName("BaseEntity lifecycle activate and deactivate methods update timestamp")
    void testDeactivateAndActivate() {
        SampleEntity entity = new SampleEntity("ENT-100");
        assertEquals("ENT-100", entity.getId());

        entity.deactivate();
        assertFalse(entity.isActive());

        entity.activate();
        assertTrue(entity.isActive());
    }
}
